[project]
name = "evo-noise"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyter>=1.1.1",
    "matplotlib>=3.10.8",
    "numpy>=2.4.2",
    "scipy>=1.17.0",
    "tqdm>=4.67.3",
]

[project.optional-dependencies]
profiling = [
    "snakeviz>=2.2.0",
]
